application: my-py-apps
version: 4
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
- url: (/) |(/home)
  script: home.py
- url: /crawler
  script: crawl.py
- url: /facebook_report
  script: facebook.py
- url: /gmail_report
  script: gmail.py
- url: /dictionary
  script: dict.py
- url: /weather_report
  script: weather.py
- url: /locations
  script: locations.py
- url: /.*
  script: home.py

libraries:
- name: jinja2
  version: "2.6"
